version: '3.8'
services:
  tachyon-concept:
    container_name: tachyon-concept
    image: tachyon_concept_img
    privileged: true
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - '8080:8080'